### PR TITLE
Enumerable methods Complete

### PR DESCRIPTION
**Pull request by Elbie-em**
-added my_each
-added my_with_index
-added my_select
-added my_all?
-added my_any?
-added my_none?
-added my_count
-added my_map(takes in block and proc)
-added my_inject

-Test cases on repl.it, link provided in readme file

Cheers

### CODE REVIEW

**Comment by Elbie-em** [comment]
**TO TSE**
Kindly note that there was a slight confusion in pushing the complete work to the repo, all checks out now. Awaiting feedback based on recent pushed data

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Elbie-em       
#### Great Job so far, but there are a few more things required. 
- [x] Build a method #multiply_els that uses #my_inject to multiply the [elements in a given array](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks)
- [x] `my_inject`
- when a symbol is specified combines each element of the collection by applying the symbol as a named method
 `p (5..10).my_inject(2, :*) ` should return `302400`
- [x] `my_all`  
- when no block or argument is given returns true when none of the collection members are false or nil:
 `p [1, true, 'hi', []].all?` should return `true`.
- when a class is passed as an argument returns true if all of the collection is a member of such class
`p ['dog',1,1].my_all?(Integer)` should return `false`
- when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
`p [3,3,3,3].my_all?(3)` should return `true`
- [x] `my_none?`:
- When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
`p ['hello'].my_none?(5)` - should return `true`
- [x] `my_any?`:
- when no block or argument is given returns true if at least one of the collection is not false or nil
`p [nil, false, nil, false].my_any?` - should return `false`
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

`p ['cat',2,32,].my_any?('cat')` should return `true`
- [x] ` my_map`
In the Odin project  you were asked to modify your my_map method to take either a proc or a block. And if both a proc and a block are given, only execute the proc. The real map doesn't have this feature.
my_proc = Proc.new { |num| num > 4 }
 `[3, 7].my_map(my_proc) { |num| num < 4 } ` should return `[false true]`
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Elbie-em** [comment]
Applied all fixes as per previous code review, please check the live demo for clarity.
Thanks in advance

**Review by mosesogwo — APPROVED** [review]
**Good work @Elbie-em:+1:. Your project is approved :heavy_check_mark:**.

**You can now merge and move ahead :stars:.**

### Status: Approved

**Pull request merged**
